// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillSwapAPI.Data;

#nullable disable

namespace SkillSwap.Migrations
{
    [DbContext(typeof(SkillSwapContext))]
    [Migration("20241217132219_CrearModelosSkillSwap")]
    partial class CrearModelosSkillSwap
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SkillSwapAPI.Models.Habilidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Habilidades");
                });

            modelBuilder.Entity("SkillSwapAPI.Models.Intercambio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HabilidadOfrecidaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HabilidadSolicitadaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioOfrecidoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioSolicitadoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HabilidadOfrecidaId");

                    b.HasIndex("HabilidadSolicitadaId");

                    b.HasIndex("UsuarioOfrecidoId");

                    b.HasIndex("UsuarioSolicitadoId");

                    b.ToTable("Intercambios");
                });

            modelBuilder.Entity("SkillSwapAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SkillSwapAPI.Models.Habilidad", b =>
                {
                    b.HasOne("SkillSwapAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SkillSwapAPI.Models.Intercambio", b =>
                {
                    b.HasOne("SkillSwapAPI.Models.Habilidad", "HabilidadOfrecida")
                        .WithMany()
                        .HasForeignKey("HabilidadOfrecidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSwapAPI.Models.Habilidad", "HabilidadSolicitada")
                        .WithMany()
                        .HasForeignKey("HabilidadSolicitadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSwapAPI.Models.Usuario", "UsuarioOfrecido")
                        .WithMany()
                        .HasForeignKey("UsuarioOfrecidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillSwapAPI.Models.Usuario", "UsuarioSolicitado")
                        .WithMany()
                        .HasForeignKey("UsuarioSolicitadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HabilidadOfrecida");

                    b.Navigation("HabilidadSolicitada");

                    b.Navigation("UsuarioOfrecido");

                    b.Navigation("UsuarioSolicitado");
                });
#pragma warning restore 612, 618
        }
    }
}
